# Generated by Django 6.0 on 2025-12-14 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.CharField(max_length=50, unique=True)),
                ('tournament_template_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
            },
        ),
        migrations.CreateModel(
            name='StatDefinition',
            fields=[
                ('stat_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('stat_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Stat Definition',
                'verbose_name_plural': 'Stat Definitions',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('participant_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('three_char_name', models.CharField(blank=True, max_length=3)),
                ('logo', models.URLField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('team_class', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Y', 'Youth')], max_length=1)),
                ('stadium_name', models.CharField(blank=True, max_length=200)),
                ('stadium_capacity', models.IntegerField(blank=True, null=True)),
                ('details_fetched', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Goalkeepers', 'Goalkeeper'), ('Defenders', 'Defender'), ('Midfielders', 'Midfielder'), ('Forwards', 'Forward'), ('Coach', 'Coach')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.country')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('tournament_stage_id', models.CharField(max_length=50)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.league')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('round', models.CharField(max_length=100)),
                ('home_event_participant_id', models.CharField(max_length=50)),
                ('away_event_participant_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('start_utime', models.BigIntegerField()),
                ('event_stage', models.CharField(choices=[('1', 'Scheduled'), ('2', 'Live'), ('3', 'Finished'), ('4', 'Postponed'), ('5', 'Cancelled')], max_length=20)),
                ('event_stage_id', models.CharField(max_length=10)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('home_full_time_score', models.IntegerField(blank=True, null=True)),
                ('away_full_time_score', models.IntegerField(blank=True, null=True)),
                ('home_halftime_score', models.IntegerField(blank=True, null=True)),
                ('away_halftime_score', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('ft_winner', models.CharField(blank=True, max_length=1, null=True)),
                ('has_live_centre', models.BooleanField(default=False)),
                ('has_lineups', models.BooleanField(default=False)),
                ('home_goal_under_review', models.IntegerField(default=0)),
                ('away_goal_under_review', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.season')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeamSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.CharField(blank=True, max_length=50)),
                ('tournament_type', models.CharField(blank=True, max_length=50)),
                ('jersey_number', models.CharField(blank=True, max_length=3)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_members', to='core.team')),
            ],
            options={
                'verbose_name': 'Team Squad Member',
                'verbose_name_plural': 'Team Squad Members',
            },
        ),
        migrations.CreateModel(
            name='MatchStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('match', 'Match'), ('1st_half', '1st Half'), ('2nd_half', '2nd Half')], max_length=20)),
                ('stat_id', models.CharField(max_length=10)),
                ('stat_name', models.CharField(max_length=100)),
                ('home_value', models.CharField(max_length=50)),
                ('away_value', models.CharField(max_length=50)),
                ('home_value_numeric', models.FloatField(blank=True, null=True)),
                ('away_value_numeric', models.FloatField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.match')),
            ],
            options={
                'verbose_name': 'Match Statistic',
                'verbose_name_plural': 'Match Statistics',
                'indexes': [models.Index(fields=['match', 'period'], name='core_matchs_match_i_2b8d56_idx'), models.Index(fields=['stat_name'], name='core_matchs_stat_na_0a652f_idx')],
                'unique_together': {('match', 'period', 'stat_id', 'stat_name')},
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['position'], name='core_player_positio_63f80f_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_name'], name='core_player_last_na_9db130_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('league', 'season_id')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season', 'start_time'], name='core_match_season__a13356_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['event_stage'], name='core_match_event_s_650fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='teamsquad',
            index=models.Index(fields=['team', 'tournament_id'], name='core_teamsq_team_id_a23c4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamsquad',
            unique_together={('team', 'player', 'tournament_id')},
        ),
    ]
