# Generated by Django 5.2.7 on 2026-01-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
