# Generated by Django 5.2.2 on 2025-12-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_player_position_alter_player_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_date',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MatchStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('stat_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('home_value', models.CharField(max_length=50)),
                ('away_value', models.CharField(max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.match')),
            ],
        ),
        migrations.DeleteModel(
            name='MatchEvent',
        ),
    ]
